name: Feature Request
description: 新機能や改善の提案
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        機能提案ありがとうございます！あなたのアイデアがプロジェクトをより良くします。

  - type: dropdown
    id: feature-type
    attributes:
      label: 機能の種類
      description: どのような種類の機能ですか？
      options:
        - 新しい開発ツールの追加（linter、formatter等）
        - pyproject.toml設定の改善
        - CI/CD の機能追加・改善
        - テンプレート質問項目の追加
        - ドキュメントの追加・改善
        - その他
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 解決したい課題
      description: この機能によってどのような問題が解決されますか？
      placeholder: |
        例：
        - 現在、◯◯の設定が不足しており、手動で追加する必要がある
        - ◯◯のツールを使いたいが、テンプレートに含まれていない
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 提案する解決策
      description: どのように実装すべきだと考えますか？
      placeholder: |
        例：
        - copier.ymlに◯◯の質問を追加
        - pyproject.tomlに◯◯の設定を追加
        - 新しいワークフローファイルを追加
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 他に検討した解決策はありますか？

  - type: textarea
    id: examples
    attributes:
      label: 参考例
      description: 他のプロジェクトやドキュメントで参考になるものがあれば記載してください
      placeholder: |
        例：
        - https://example.com/similar-feature
        - poetry-plugin-export の設定例

  - type: checkboxes
    id: contribution
    attributes:
      label: コントリビューション
      options:
        - label: この機能の実装にPRで貢献できます
        - label: ドキュメント作成に協力できます
        - label: テストに協力できます

  - type: checkboxes
    id: checklist
    attributes:
      label: チェックリスト
      options:
        - label: 既存のIssueやPRを確認し、同様の提案がないことを確認しました
          required: true
        - label: この機能がテンプレートの設計思想（シンプル・汎用性）に合致していると考えています
          required: true
